#!/bin/bash
# NorthAfrica Script - LOG USER ACCOUNT

NC="\033[0m"
GREEN="\033[0;32m"
CYAN="\033[1;36m"
RED="\033[0;31m"

clear
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "        USER CREATE ACCOUNT LOG"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

LOGFILE="/etc/user-create/user.log"

if [[ -f "$LOGFILE" ]]; then
    cat "$LOGFILE"
else
    echo -e "${RED}No user-create log found${NC}"
fi

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
read -n1 -s -r -p "Press Enter to return to menu"

menu
