#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Developer  » Abdul NorthAfrica࿐
# Email      » yourmail@example.com
# Telegram   » https://t.me/YourChannel
# Group      » https://t.me/YourGroup
# Whatsapp   » wa.me/+212600000000
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ MULTI-LOGIN NOTIFICATION ⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Limit IP : </code><code>$iplimit</code>
<code>────────────────────</code>
<b>Telegram :</b> <a href='https://t.me/YourChannel'>@YourChannel</a>
<b>Group :</b> <a href='https://t.me/YourGroup'>Join Group</a>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function vmip(){
#LIMIT VMESS IP
echo -n > /var/log/xray/access.log
sleep 1
data=( `ls /etc/kyt/limit/vmess/ip`)
# Script by Abdul NorthAfrica
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        cekcek=$(echo -e "$ehh" | wc -l)
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
            systemctl restart xray >> /dev/null 2>&1
            rm -rf /etc/kyt/limit/vmess/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

function vlip(){
#LIMIT VLESS IP
echo -n > /var/log/xray/access.log
sleep 1
data=( `ls /etc/kyt/limit/vless/ip`)
# Script by Abdul NorthAfrica
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vless/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        cekcek=$(echo -e "$ehh" | wc -l)
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^### $user $exp/d" /etc/vless/.vless.db
            systemctl restart xray >> /dev/null 2>&1
            rm -rf /etc/kyt/limit/vless/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

function trip(){
#LIMIT TROJAN IP
echo -n > /var/log/xray/access.log
sleep 1
data=( `ls /etc/kyt/limit/trojan/ip`)
# Script by Abdul NorthAfrica
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        cekcek=$(echo -e "$ehh" | wc -l)
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
            systemctl restart xray >> /dev/null 2>&1
            rm -rf /etc/kyt/limit/trojan/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

if [[ ${1} == "vmip" ]]; then
    vmip
elif [[ ${1} == "vlip" ]]; then
    vlip
elif [[ ${1} == "trip" ]]; then
    trip
fi