#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Developer  » Abdul NorthAfrica࿐
# Email      » yourmail@example.com
# Telegram   » https://t.me/YourChannel
# Group      » https://t.me/YourGroup
# Whatsapp   » wa.me/+212600000000
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function send_log(){
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ QUOTA LIMIT REACHED ⚠️</b>
<code>────────────────────</code>
<code>Username     :</code> <code>$user</code>
<code>Used Traffic :</code> <code>$total</code>
<code>Quota Limit  :</code> <code>$cekdulu</code>
<code>────────────────────</code>
<b>Channel :</b> <a href='https://t.me/YourChannel'>@YourChannel</a>
<b>Group :</b> <a href='https://t.me/YourGroup'>Join Support</a>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function con() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

function cekvmess(){
    data=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/vmess
    for user in "${data[@]}"; do
        mkdir -p /tmp/quota
        data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        inb=$(echo "$data" | sed -n 1p)
        outb=$(echo "$data" | sed -n 2p)
        quota0=$(( inb + outb ))
        file="/etc/limit/vmess/${user}"
        if [ -e "$file" ]; then
            quota1=$(cat "$file")
            quota2=$(( quota0 + quota1 ))
            echo "$quota2" > "$file"
        else
            echo "$quota0" > "$file"
        fi
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

function cekvless(){
    data=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/vless
    for user in "${data[@]}"; do
        mkdir -p /tmp/quota
        data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        inb=$(echo "$data" | sed -n 1p)
        outb=$(echo "$data" | sed -n 2p)
        quota0=$(( inb + outb ))
        file="/etc/limit/vless/${user}"
        if [ -e "$file" ]; then
            quota1=$(cat "$file")
            quota2=$(( quota0 + quota1 ))
            echo "$quota2" > "$file"
        else
            echo "$quota0" > "$file"
        fi
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

function cektrojan(){
    data=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/trojan
    for user in "${data[@]}"; do
        mkdir -p /tmp/quota
        data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        inb=$(echo "$data" | sed -n 1p)
        outb=$(echo "$data" | sed -n 2p)
        quota0=$(( inb + outb ))
        file="/etc/limit/trojan/${user}"
        if [ -e "$file" ]; then
            quota1=$(cat "$file")
            quota2=$(( quota0 + quota1 ))
            echo "$quota2" > "$file"
        else
            echo "$quota0" > "$file"
        fi
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

function vmess(){
    while true; do
        sleep 30
        cekvmess
        data=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
        for user in "${data[@]}"; do
            if [ -e /etc/vmess/${user} ]; then
                cekdulu=$(cat /etc/vmess/${user})
                if [[ -n $cekdulu && -e /etc/limit/vmess/${user} ]]; then
                    pakai=$(cat /etc/limit/vmess/${user})
                    if [[ $pakai -gt $cekdulu ]]; then
                        exp=$(grep -w "^### $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
                        systemctl restart xray >/dev/null 2>&1
                        total=$(con $(cat /etc/limit/vmess/${user}))
                        send_log
                        rm -rf /etc/limit/vmess/${user}
                    fi
                fi
            fi
        done
    done
}

function vless(){
    while true; do
        sleep 30
        cekvless
        data=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
        for user in "${data[@]}"; do
            if [ -e /etc/vless/${user} ]; then
                cekdulu=$(cat /etc/vless/${user})
                if [[ -n $cekdulu && -e /etc/limit/vless/${user} ]]; then
                    pakai=$(cat /etc/limit/vless/${user})
                    if [[ $pakai -gt $cekdulu ]]; then
                        exp=$(grep -w "^#& $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^### $user $exp/d" /etc/vless/.vless.db
                        systemctl restart xray >/dev/null 2>&1
                        total=$(con $(cat /etc/limit/vless/${user}))
                        send_log
                        rm -rf /etc/limit/vless/${user}
                    fi
                fi
            fi
        done
    done
}

function trojan(){
    while true; do
        sleep 30
        cektrojan
        data=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
        for user in "${data[@]}"; do
            if [ -e /etc/trojan/${user} ]; then
                cekdulu=$(cat /etc/trojan/${user})
                if [[ -n $cekdulu && -e /etc/limit/trojan/${user} ]]; then
                    pakai=$(cat /etc/limit/trojan/${user})
                    if [[ $pakai -gt $cekdulu ]]; then
                        exp=$(grep -w "^#! $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
                        systemctl restart xray >/dev/null 2>&1
                        total=$(con $(cat /etc/limit/trojan/${user}))
                        send_log
                        rm -rf /etc/limit/trojan/${user}
                    fi
                fi
            fi
        done
    done
}

# Execute based on argument
case ${1} in
    vmess) vmess ;;
    vless) vless ;;
    trojan) trojan ;;
esac