#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » savagetech56࿐
# Email      » johntezali56@gmail.com
# telegram   » https://t.me/ToxicSavage 
# whatsapp   » wa.me/+254716637803
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# premium࿐

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'
BGWHITE='\e[0;100;37m'

red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear

echo -e ""
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}  ${BGWHITE}            MENU MANAGER SHADOWSHOCKS           ${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}   ${NC}[${GREEN}01${NC}]${YELL} Create Account Shadowshocks WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}02${NC}]${YELL} Create Trial Shadowshocks WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}03${NC}]${YELL} Delete Account Shadowsocks WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}04${NC}]${YELL} Renew Shadowsocks Account${NC}"
echo -e " ${NC}   ${NC}[${GREEN}05${NC}]${YELL} Check Shadowsocks login Account${NC}"
echo -e " ${NC}   ${NC}[${RED}0X${NC}]${RED} ComeBack Menu${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e ""
read -p "  Select From Options [ 1-5 / 0X ] »» " menu

case $menu in
1 | 01)
    addss
    ;;
2 | 02)
    trialss
    ;;
3 | 03)
    delss
    ;;
4 | 04)
    renewss
    ;;
5 | 05)
    cekss
    ;;
0 | 00 | x | X | 0x | 0X)
    clear
    menu
    ;;    
*)
    m-ssws
    ;;
esac
